//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practika.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academics
    {
        public int id_akademiki { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public Nullable<System.DateTime> date_birth { get; set; }
        public string specialization { get; set; }
        public string year_of_assignment { get; set; }
    }
}
