//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practika.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int id_exam { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> kod { get; set; }
        public Nullable<int> reg_num { get; set; }
        public Nullable<int> tab_num { get; set; }
        public string auditorium { get; set; }
        public Nullable<int> estimation { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
