//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practika.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hight_School_student
    {
        public int id { get; set; }
        public string surname { get; set; }
        public string @object { get; set; }
        public string school { get; set; }
        public Nullable<double> scores { get; set; }
    }
}
